// Valentina Franco Avalos
// 000416067
// valentina.francoa@upb.edu.co

//R1 - Contador posición valor inicial (16384) 
//R2 - Contador posición valor actual
//Posición máxima = 24575 
//Input = 24576

@16384  //GUARDO EL VALOR INICIAL EN EL ESPACIO DEL CONTADOR INICIAL
D=A
@R1
M=D  

(LOOP)
@R1       //PRIMER LOOP: GUARDO EN EL CONTADOR DE POSICIÓN QUE ES DONDE ESTAMOS ACTUALMENTE EL VALOR DEL CONTADOR INICIAL QUE ES DONDE VAMOS A COMENZAR EL PROGRAMA
D=M
@R2
M=D

@24576    //GUARDAMOS EL VALOR DEL INPUT EN EL REGISTRO D
D=M
@70
D=D-A
@LOOP    //VUELVE A PREGUNTAR EL INPUT
D;JNE   //SI DA D=0 ES POR QUE LA LETRA PRESIONADA ES F 

(SEGUNDOLOOP)
@R2      //POSICIÓN ACTUAL EN D
D=M
@24575   //ESPECIFICAMOS DONDE TERMINA NUESTRA PANTALLA
D=D-A    //OBTENER SI LA POSICIÓN ACTUAL ES MENOR O IGUAL A LA POSICIÓN MAXIMA(MENOR A 0)
@LOOP
D;JGT    //SI ESTO NO SE CUMPLE SIGNIFICA QUE ESTAMOS TODAVIA DENTRO DE LA PANTALLAI ESTO NO SE CUMPLE SIGNIFICA QUE ESTAMOS TODAVIA DENTRO DE LA PANTALLA

@R2      
A=M      // A PASA A SER LA DIRRECION ACTUAL DE LA PANTALLA DONDE ESTAMOS 
M=-1    //LLENAR CON 1 

@R2
M=M+1   //R2++ CAMBIAMOS DE PIXEL SUCESIVAMENTE

@SEGUNDOLOOP  //SALTA PARA IR PREGUNTANDO SI SEGUIMOS EN PANTALLA O SALIMOS DEL LOOP DE LLENAR CON PIXELES
0;JMP
   
    